### ISSUE TITLE
Would it be OK to eventually add these to FreeCAD/FreeCAD-library

### ISSUE THREAD

**Issue by luzpaz** [rkrenzler/ose-piping-library#1]
Ref: https://github.com/FreeCAD/FreeCAD-library 
Also do you know about https://github.com/oddtopus/flamingo ?

**Comment by rkrenzler** [comment]
I have never heard about flamingo. Thank you very much!
I will check FreeCAD-library again.
I will consider to join the projects above.

Initially I planned to release my macros under Public Domain, but flamingo uses LGPL...

**Comment by luzpaz** [comment]
I think that FreeCAD uses LGPL as well

**Comment by rkrenzler** [comment]
You are correct https://github.com/FreeCAD/FreeCAD/blob/master/COPYING

**Comment by rkrenzler** [comment]
I just looked at https://github.com/FreeCAD/FreeCAD-library.
These are more about complete parts and there are only few pipe parts. Nevertheless I possible will use some of these parts to improve my macros.
